### ISSUE TITLE
use meson to install icon files

### ISSUE THREAD

**Issue by sunweaver** [IKRadulov/mate-window-applets#12]
Please drop the install.sh script and implement icon file installation via meson. Thanks!

**Comment by IKRadulov** [comment]
Meson doesn't handle uninstall of files with custom build command . The way the script it is , it can uninsall and install the icons from/to the specified directory. It is not hard to package the icons , as for example see my arch linux pkg . Also I am reasearched at the moment how the xfce4-windowck-plugin is getting its icons and I will drop support for the old icon themes .
