### ISSUE TITLE
meson ends with  error

### ISSUE THREAD

**Issue by brokoli-mate** [IKRadulov/mate-window-applets#3]
**Meson encountered an error in file meson.build, line 31, column 0:
Native dependency 'libmatepanelapplet-4.0' not found**
but **sudo apt install libmate-panel-applet-4-1** says that it is already latest version. 

Ubuntu MATE 17.04

**Comment by IKRadulov** [comment]
It seems that pkg-config can't find libmate-panel-applet . Did you install libmate-panel-applet-dev ? If not install it and then try to compile it . If so I will include this dependancy for ubuntu based systems.

**Comment by brokoli-mate** [comment]
It is alraedy installed

**Comment by IKRadulov** [comment]
Strange ! Anyway the issue is resolved it seems , so I will close it .
