### ISSUE TITLE
window buttons applet crashes (v1.4)

### ISSUE THREAD

**Issue by brokoli-mate** [IKRadulov/mate-window-applets#4]
So I installed them succesfully, but now buttons applet crashes.

**The output from terminal when running panel with applet on it:**
** (mate-panel:2479): WARNING **: Error setting property: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by IKRadulov** [comment]
This doesn't tell me anything . 
In terminal : 
1.Remove applet
2./usr/lib/mate-applets/mate-window-applets/window-buttons/window-buttons-applet in terminal
3.Add applet to panel.
4.Paste me the output .

**Comment by brokoli-mate** [comment]
no such file or directory

the only files in **/usr/lib/mate-applets/mate-window-applets** are: **About-Settings.glade  __pycache__**

but **/usr/lib/x86_64-linux-gnu/mate-applets/mate-window-applets/window-buttons/window-buttons-applet** runs with no message and no applet appair

**Comment by IKRadulov** [comment]
I wonder how did the applet path mix with x86_64-linux-gnu .
Go into build directory and in terminal type " meson configure" and paste me the output .

**Comment by brokoli-mate** [comment]
Error during basic setup:

Neither directory contains a build file meson.build.

**Comment by brokoli-mate** [comment]
When I try to add the applet while running in terminal  **/usr/lib/x86_64-linux-gnu/mate-applets/mate-window-applets/window-buttons/window-buttons-applet** I get this:
(window-buttons-applet:5195): GLib-GIO-ERROR **: Settings schema 'org.mate.window-applets.window-buttons' is not installed

**Comment by IKRadulov** [comment]
For the first could you paste me "mesonconf" from build dir . It seems your version doesn't accept configure option . 
For the second . you forget to recompile the schemas . if you did recompile them does 
"ls /usr/share/glib-2.0/schemas | grep org.mate.window-applets" output something ?

**Comment by brokoli-mate** [comment]
There is no mesonconf file.

What do you mean by recompile schemas? how should I do that?
**ls /usr/share/glib-2.0/schemas | grep org.mate.window-applets** returns
**org.mate.window-applets.gschema.xml**

**Comment by IKRadulov** [comment]
How dull I am forget to mention it in build instructions ... How stuped of me . 
You should do "sudo glib-compile-schemas /usr/share/glib-2.0/schemas  " after install . As for the path it should be fixed in master now.

**Comment by brokoli-mate** [comment]
that worked, thanks
