### ISSUE TITLE
window buttons padding

### ISSUE THREAD

**Issue by brokoli-mate** [IKRadulov/mate-window-applets#6]
Padding applies only after resizing the panel and drops after reboot/restart panel/readd applet(the value still the same but to apply it you need to resize panel again)

**Comment by IKRadulov** [comment]
Should be fixed in master

**Comment by brokoli-mate** [comment]
Now it's almost perfect. The only thing i would change - remove squares when hovering with mouse(in previous versions it was like that), but it is not an issue. Thank you, Great work.

**Comment by IKRadulov** [comment]
I plan to remove it . The privious versions were made with event boxes . This is with buttons . So I have to style the buttons with custom css . I will include that in future version .
