### ISSUE TITLE
Extreme memory consumption

### ISSUE THREAD

**Issue by svenhsia** [IKRadulov/mate-window-applets#9]
I just experienced a crash of desktop environment because of the memory consumption of mate-windows-button applet (as shown in the screen shot below). I tried to reproduce this bug but failed.

Some information may be useful for detecting the bug. I was using compiz windows manager (instead of default Macro). The problem happened after I set the panel to be transparent. I was running chrome. I was using vala-appmenu applet.
However, I tried to repeat the same things that I was doing when the problem happened. It did not return again.

![screenshot at 2017-09-17 21-51-33](https://user-images.githubusercontent.com/22543193/30524763-c3b85fbe-9bf9-11e7-89cd-984b087850eb.png)

**Comment by IKRadulov** [comment]
Is it compiz reloaded or just compiz ? I will try to reproduce it .

**Comment by svenhsia** [comment]
I uninstalled compiz but this problem just happened again. So maybe it has nothing with compiz.

**Comment by IKRadulov** [comment]
Here are the following steps to debug .
1. Install gdb.
2. Run gdb /usr/lib/mate-applets/mate-window-applets/window-buttons/window-buttons-applet
When in gdb 
3. Remove applet from panel
4. Type start 
5. Add applet to panel
6. When memory consumation gets high press control + c .
5. Type backtrace
6. Paste me the output

**Comment by svenhsia** [comment]
I haven't figured out how to reproduce the problem. When I figured it out, I will follow these steps to get debug information for you.

**Comment by IKRadulov** [comment]
I was able to replacate the issue . 
Making it a bug . 
The only thing left is to find the problem and fix it.

**Comment by IKRadulov** [comment]
Should bbe fixed in master . Reopen if it is not .
